apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: auth
        image: harbor.bahur/auth-demo/auth-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
