apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: frontend
        image: harbor.bahur/frontend-demo/frontend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"