apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: tasks
        image: harbor.bahur/tasks-demo/tasks-api:latest
        env:
        - name: AUTH_ADDRESS
          value: "auth-service.node-test"
        - name: TASKS_FOLDER
          value: tasks
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"